### ISSUE TITLE
Not in project

### ISSUE THREAD

**Issue by AlexFransis** [ZachMassia/PlatformIO-Mode#10]
Hello,

Thank you for this package but I am getting an error every time I try to run a Command. It says that I am not a project.

My work around is to initialize a git repo for my project. How can I make projectile recognize the platformio.ini and assign it as a project?

Thank you

**Comment by AlexFransis** [comment]
I am using Spacemacs btw!

**Comment by ZachMassia** [comment]
Hi Alex,

See if adding this to your config works.

`(add-to-list 'projectile-project-root-files "platformio.ini")`

**Comment by AlexFransis** [comment]
Hello Zach,

Thank you this solved my problem!

**Comment by ZachMassia** [comment]
No problem. Glad I could help!
