### ISSUE TITLE
i can't get work the mode. There is an error related with platformio-setup-compile-buffer function

### ISSUE THREAD

**Issue by brolin** [ZachMassia/PlatformIO-Mode#4]
This is the error when open emacs with debug-init:

```
Debugger entered--Lisp error: (void-function platformio-setup-compile-buffer)
  (platformio-setup-compile-buffer)
  eval-buffer(#<buffer  *load*> nil "/home/brolin/.emacs" nil t)  ; Reading at buffer position 9002
  load-with-code-conversion("/home/brolin/.emacs" "/home/brolin/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\262
```
Do you have an idea or any clue of what happens?

**Comment by ZachMassia** [comment]
Hi @brolin,

Could you link me your `.emacs` file in a gist?

Thanks.

**Comment by brolin** [comment]
Hi @ZachMassia 

I have huge .emacs file with multiple settings, maybe the error is there but i don't know lisp to detect what is. Here is my .emacs https://gist.github.com/brolin/2104a30ad52039279018

Thanks a lot.

**Comment by ZachMassia** [comment]
@brolin, from what I can tell, the only thing missing might be the call to `(require 'platformio-mode)` before calling `platformio-setup-compile-buffer`. 

Looking at [my own config](https://github.com/ZachMassia/.emacs.d/blob/master/emacs.org#c), that's the only real difference.

Let me know if that fixes it for you, and I'll update the readme accordingly.

**Comment by brolin** [comment]
Thanks!!!

after add that line. Now all works fine!!

best regards!
-
b

**Comment by ZachMassia** [comment]
Great, enjoy!
